
import LeftSidebar from '@/components/comps/LeftSidebar'
import './globals.css'
import RightSidebar from '@/components/comps/RightSidebar'
import Topbar from '@/components/comps/Topbar'
import AuthContextProvider from '@/context/AuthContextProvider'
import MobileNavigation from '@/components/comps/MobileNavigation'
import { inter } from '@/constants'
import { ThemeProvider } from '@/components/comps/Theme-provider'

export const metadata = {
  title: 'Scroll',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white dark:bg-dark-2`}  >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthContextProvider>
            <div className='grid grid-cols-1 md:grid-cols-12'>
              <Topbar />
              <LeftSidebar />
              <section className='scrollbar-hide col-span-6 bg-gray-200 dark:bg-dark-2   h-screen overflow-y-auto'>
                {children}
              </section>
              <RightSidebar />
              <MobileNavigation />
            </div>
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
